[colors]
[colors.primary]
background = "0x282828"
foreground = "0xd4be98"

[colors.normal]
black = "0x3c3836"
red = "0xea6962"
green = "0xa9b665"
yellow = "0xd8a657"
blue = "0x7daea3"
magenta = "0xd3869b"
cyan = "0x89b482"
white = "0xd4be98"

[colors.bright]
black = "0x3c3836"
red = "0xea6962"
green = "0xa9b665"
yellow = "0xd8a657"
blue = "0x7daea3"
magenta = "0xd3869b"
cyan = "0x89b482"
white = "0xd4be98"

[env]
TERM = "xterm-256color"

[font]
normal = { family = "Cascadia Mono NF", style = "Regular" }
bold = { family = "Cascadia Mono NF", style = "Bold" }
italic = { family = "Cascadia Mono NF", style = "Italic" }
size = 9

[window]
padding.x = 14
padding.y = 14
decorations = "None"

[keyboard]
bindings = [
{ key = "F11", action = "ToggleFullscreen" }
]
